name: Metrics

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'


    - name: Install dependencies
      working-directory: ./app
      run: |
        pip install poetry 
        poetry install

    - name: Static Analysis
      working-directory: ./app
      run: |
        poetry run flake8 

    - name: Run tests with pytest
      working-directory: ./app
      run: |
        poetry run pytest --benchmark-skip
        

    - name: Benchmark response times
      working-directory: ./app
      run: |
        poetry run pytest --benchmark-only --benchmark-save-data

    - name: Measure code coverage
      working-directory: ./app
      run: |
        poetry run pytest --cov=app --cov-report=term-missing --cov-fail-under=0

    - name: Set up flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'

    - name: Install dependencies
      working-directory: ./frontend
      run: |
        flutter pub get


    - name: Lint
      working-directory: ./frontend
      run: |
        flutter pub run lint
    
    - name: Analyze
      working-directory: ./frontend
      run: |
        flutter pub run analyze

